version: '3.8'

services:
  postgres:
    container_name: gestao-vagas-postgres_c
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao-vagas_db
